on: push
jobs:
  fist-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Check python version
      - run: python --version

      - name: Install Jupyter Notebook
      - run: python -m pip install jupyter

      - name: Convert Jypyter Notebook
      - run: jupyter nbconvert --to python launching_into_ml/improve_data_quality/improve_data_quality.ipynb

      - name: Run Jypyter Notebook
      - run: python launching_into_ml/improve_data_quality/improve_data_quality.ipynb