on: push
jobs:
  fist-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Check python version
        run: python --version

      - name: Install Jupyter Notebook
        run: python -m pip install jupyter
        
      - name: Install Jupyter Convertor
        run: python -m pip install nbconvert

      - name: Run Jypyter Notebook
        run: python launching_into_ml/improve_data_quality/improve_data_quality.ipynb
      
      - name: Upload static site content
        uses: actions/upload-artifact@v3
        with:
          name: static-site
          path: .