on: push
jobs:
  fist-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Set up python
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install --no-cache-dir -r requirements.txt

      - name: Convert And Run Jypyter Notebook
        run: jupyter nbconvert --to notebook --execute improve_data_quality/improve_data_quality.ipynb
      
      - name: Upload static site content
        uses: actions/upload-artifact@v3
        with:
          name: static-site
          path: .