on: push
jobs:
  fist-jobs:
    runs-on: ubuntu-latest
    steps:
      - run: python --version
      - run: jupyter nbconvert --to python launching_into_ml/improve_data_quality/improve_data_quality.ipynb
      - run: python launching_into_ml/improve_data_quality/improve_data_quality.ipynb